### PR TITLE
Added home page with responsiveness

### PR DESCRIPTION
**Pull request by TusharJade**
### Have a look at my home page guys made it responsive also

Screenshot (31)

### CODE REVIEW

**Review by sakshi006 — APPROVED** [review]
Good to go!

**Review by Balakumar3018 — COMMENTED** [review]
everything looks good
Suggestions - looks better if you highlight the cards when hover it

**Comment by TusharJade** [comment]
> everything looks good
> Suggestions - looks better if you highlight the cards when hover it


Yeah thanks bro, forgot that, will gave hover effect now

**Review by TusharJade — COMMENTED** [review]
added hover effect

**Pull request merged**
